-- fotisp-edge D1 Seed Data
-- Generated: 2026-08-02T16:52:49.742Z

BEGIN TRANSACTION;

-- POSTS
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, content, author, categories, published_at) VALUES ('e272cf98-c97b-4651-88a4-537283ce2523', 'first-consulting-contract', '6 Steps to Getting Your First Consulting Contract', 'Breaking into consulting is one of the most rewarding career moves you can make.', 'Breaking into consulting is rewarding but landing your first contract can feel overwhelming...', 'Admin', '["Business","Consulting"]', 1602633600);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, content, author, categories, published_at) VALUES ('67f511c7-93f6-4e5d-943e-e5b3664e2f4c', 'enforce-non-compete', 'Can You Enforce a Non-Compete?', 'Non-compete agreements are one of the most contested areas of employment law.', 'Non-compete agreements (also called restrictive covenants) are contractual clauses...', 'Admin', '["Law","Business"]', 1602633600);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, content, author, categories, published_at) VALUES ('c20f943b-fa66-426c-b956-3b55e47aae00', 'venture-capital-rules', 'The Rules of Venture Capital in 2024', 'VC has changed dramatically. Here''s what founders need to understand about how the game is played.', 'The venture capital landscape has shifted significantly over the past several years...', 'Admin', '["Finance","Startups"]', 1602633600);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, content, author, categories, published_at) VALUES ('545ae2fe-859d-4d9b-bd48-24036f69e0df', 'growth-hacking-customer-feedback', 'Growth Hacking With Customer Feedback', 'The fastest-growing companies don''t guess — they build systematic feedback loops.', 'The fastest-growing companies build systematic feedback loops that fuel product decisions...', 'Admin', '["Marketing","Growth"]', 1602633600);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, content, author, categories, published_at) VALUES ('cae2f724-af05-4654-b168-c5caa5971880', 'brand-identity-that-lasts', 'How to Build a Brand Identity That Lasts', 'Brand identity is more than a logo — it''s every interaction a customer has with your business.', 'Brand identity is more than a logo. It is the sum of every interaction a customer has...', 'Admin', '["Marketing","Business"]', 1602633600);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, content, author, categories, published_at) VALUES ('5ec95342-db8e-4417-9b3e-bade55692a84', 'reducing-operational-complexity', 'Reducing Operational Complexity Through Automation', 'Every manual process is a liability. Learn how to identify and automate the right workflows.', 'Every manual process is a liability. It consumes time, introduces human error...', 'Admin', '["Operations","Technology"]', 1602633600);

-- FTS INDEX
INSERT OR IGNORE INTO posts_fts (rowid, title, excerpt, content) SELECT rowid, title, excerpt, content FROM posts WHERE slug = 'first-consulting-contract';
INSERT OR IGNORE INTO posts_fts (rowid, title, excerpt, content) SELECT rowid, title, excerpt, content FROM posts WHERE slug = 'enforce-non-compete';
INSERT OR IGNORE INTO posts_fts (rowid, title, excerpt, content) SELECT rowid, title, excerpt, content FROM posts WHERE slug = 'venture-capital-rules';
INSERT OR IGNORE INTO posts_fts (rowid, title, excerpt, content) SELECT rowid, title, excerpt, content FROM posts WHERE slug = 'growth-hacking-customer-feedback';
INSERT OR IGNORE INTO posts_fts (rowid, title, excerpt, content) SELECT rowid, title, excerpt, content FROM posts WHERE slug = 'brand-identity-that-lasts';
INSERT OR IGNORE INTO posts_fts (rowid, title, excerpt, content) SELECT rowid, title, excerpt, content FROM posts WHERE slug = 'reducing-operational-complexity';

-- EVENTS
INSERT OR IGNORE INTO fotisp_events (id, slug, title, excerpt, event_date, event_time, location, is_recurring, category_slug, published_at) VALUES ('7f880af5-7adb-4234-bf19-7e0a26d3e1a8', 'q1-strategy-review', 'Q1 Strategy Review & Planning Session', 'Annual Q1 strategy review where senior leadership reviews KPI performance.', '2024-03-15', '09:00 – 17:00', 'London, UK — Hilton Bankside', 0, 'corporate', 1705276800);
INSERT OR IGNORE INTO fotisp_events (id, slug, title, excerpt, event_date, event_time, location, is_recurring, category_slug, published_at) VALUES ('5b8e2ba5-0b8a-4db1-aa30-105e72eb4fc2', 'digital-transformation-summit', 'Digital Transformation Summit', 'A full-day summit for C-suite executives and technology leaders.', '2024-04-22', '08:30 – 18:00', 'Athens, Greece — Metropolitan Expo', 0, 'technology', 1706745600);

-- PORTFOLIO
INSERT OR IGNORE INTO fotisp_portfolio (id, slug, title, excerpt, category_slug, published_at) VALUES ('ded3efd3-d6c1-4fe3-83a8-8b14588e5207', 'cutting-costs-to-grow-stronger', 'Cutting Costs to Grow Stronger', 'How we helped a consumer goods company reduce operational overhead by 31%.', 'consumer-markets', 1685577600);
INSERT OR IGNORE INTO fotisp_portfolio (id, slug, title, excerpt, category_slug, published_at) VALUES ('ea3d5410-a292-49ae-8efb-e89c4f313a87', 'helping-global-media-firm-optimize', 'Helping a Global Media Firm Optimize Business', 'Strategic restructuring for a global media conglomerate with 14 brands.', 'media', 1678838400);
INSERT OR IGNORE INTO fotisp_portfolio (id, slug, title, excerpt, category_slug, published_at) VALUES ('9a53ea35-35ee-446c-b449-435afaf2141b', 'app-for-branch-managers', 'An App That Helps Branch Managers Manage', 'Mobile-first operations dashboard for 200+ branch managers.', 'information-technology', 1668038400);
INSERT OR IGNORE INTO fotisp_portfolio (id, slug, title, excerpt, category_slug, published_at) VALUES ('0a5e654c-d5cb-4b53-b9eb-705a3e7fab96', 'a-strategic-overhaul', 'A Strategic Overhaul', 'Complete strategic repositioning for a legacy media brand navigating disruption.', 'media', 1659312000);
INSERT OR IGNORE INTO fotisp_portfolio (id, slug, title, excerpt, category_slug, published_at) VALUES ('c666c9dc-5916-4174-91a0-bda76fcd5d44', 'enhancing-bi-through-ai', 'Enhancing Business Intelligence Through AI', 'Deploying ML models to surface actionable intelligence from enterprise data.', 'technology', 1649980800);
INSERT OR IGNORE INTO fotisp_portfolio (id, slug, title, excerpt, category_slug, published_at) VALUES ('451baa81-b7cc-42e5-9588-05e60dc60e97', 'improving-care-provider-experience', 'Improving the Care Provider Experience', 'UX research and portal redesign for a national healthcare provider network.', 'healthcare', 1638316800);

-- SERVICES
INSERT OR IGNORE INTO fotisp_services (id, slug, title, excerpt, icon, published_at) VALUES ('d58685af-b2ae-48c2-8a3d-54aa81618f95', 'kpi-reporting', 'KPI Reporting & Performance Analytics', 'A measurable value that demonstrates how effectively a company achieves key business objectives.', '📊', 1577836800);
INSERT OR IGNORE INTO fotisp_services (id, slug, title, excerpt, icon, published_at) VALUES ('ae63680a-9868-4cf6-b94c-28349859a733', 'it-business-consulting', 'IT Business Consulting', 'Analyzing business objectives to determine how technology can deliver optimal results.', '💼', 1577836800);
INSERT OR IGNORE INTO fotisp_services (id, slug, title, excerpt, icon, published_at) VALUES ('b74cf682-14ae-44eb-a346-3134aa3c5937', 'strategic-planning', 'Strategic Planning', 'Long-term direction setting with measurable milestones and success metrics.', '🗺️', 1577836800);
INSERT OR IGNORE INTO fotisp_services (id, slug, title, excerpt, icon, published_at) VALUES ('1f590d4d-7968-4100-9c05-422ed97aa970', 'reverse-logistics', 'Reverse Logistics', 'Moving goods from their final destination for value capture or proper disposal.', '🔄', 1577836800);
INSERT OR IGNORE INTO fotisp_services (id, slug, title, excerpt, icon, published_at) VALUES ('4581a468-c1d7-4ebe-8f23-6d7b1f3acf70', 'operations-management', 'Operations Management', 'Streamlining internal processes to maximize efficiency and reduce overhead.', '⚙️', 1577836800);
INSERT OR IGNORE INTO fotisp_services (id, slug, title, excerpt, icon, published_at) VALUES ('3d7fda82-753f-4d71-a999-f9e6fb6086d4', 'market-research', 'Market Research', 'Data-driven insights to inform your business development strategy.', '🔍', 1577836800);

-- TEAM
INSERT OR IGNORE INTO fotisp_team (id, slug, name, role, bio, social_json) VALUES ('67028965-2cbc-4b77-9774-849b7470b42f', 'martin-dylon', 'Martin Dylon', 'Chief Financial Officer', 'Over 20 years of financial leadership experience across financial services, consumer goods, and professional services.', '{"linkedin":"#","twitter":"#"}');
INSERT OR IGNORE INTO fotisp_team (id, slug, name, role, bio, social_json) VALUES ('0b49aaa2-2d4b-4976-9554-a359eb249b7f', 'james-flanagan', 'James Flanagan', 'Chief Network Officer', '15 years building high-value professional networks across Europe, North America, and Southeast Asia.', '{"linkedin":"#","twitter":"#"}');
INSERT OR IGNORE INTO fotisp_team (id, slug, name, role, bio, social_json) VALUES ('74a8120e-ad07-47cc-8b3e-1f3ec64c5a1d', 'mark-price', 'Mark Price', 'Chief Diversity Officer', 'Driving inclusive excellence across the organization with deep expertise in DEI strategy and implementation.', '{"linkedin":"#","twitter":"#"}');
INSERT OR IGNORE INTO fotisp_team (id, slug, name, role, bio, social_json) VALUES ('16b2dd9e-bbfd-4201-98e8-c7f732f5c655', 'christopher-walker', 'Christopher Walker', 'Chief Commercial Officer', 'Commercial strategy and revenue growth across complex, multi-market B2B environments.', '{"linkedin":"#","twitter":"#"}');
INSERT OR IGNORE INTO fotisp_team (id, slug, name, role, bio, social_json) VALUES ('0ab2cbda-30b7-47a8-bd48-fbfd43e032a2', 'mark-weathers', 'Mark Weathers', 'Tax Leader', 'Specialist in international tax strategy, transfer pricing, and M&A tax advisory.', '{"linkedin":"#"}');
INSERT OR IGNORE INTO fotisp_team (id, slug, name, role, bio, social_json) VALUES ('791fbc19-f647-4c72-acc2-a5af1906cab2', 'vicki-cheng', 'Vicki Cheng', 'Senior Partner', '18 years in organizational transformation, leadership development, and people strategy across 14 countries.', '{"linkedin":"#","twitter":"#"}');

COMMIT;
